# Generated by Django 5.1.4 on 2025-06-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='items/')),
                ('category', models.CharField(choices=[('vintage', 'Vintage'), ('reworked', 'Reworked'), ('minimal', 'Minimal'), ('floral', 'Floral'), ('denim', 'Denim'), ('boho', 'Boho')], max_length=50)),
            ],
        ),
    ]
