# Generated by Django 5.1.4 on 2025-06-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
