# Generated by Django 5.1.4 on 2025-06-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
